// FRAM_BUFF.v

// Generated using ACDS version 15.1 193

`timescale 1 ps / 1 ps
module FRAM_BUFF (
		input  wire [9:0]  data_a,    //  ram_input.datain_a
		input  wire [9:0]  data_b,    //           .datain_b
		input  wire [19:0] address_a, //           .address_a
		input  wire [19:0] address_b, //           .address_b
		input  wire        wren_a,    //           .wren_a
		input  wire        wren_b,    //           .wren_b
		input  wire        clock_a,   //           .clock_a
		input  wire        clock_b,   //           .clock_b
		output wire [9:0]  q_a,       // ram_output.dataout_a
		output wire [9:0]  q_b        //           .dataout_b
	);

	FRAM_BUFF_ram_2port_151_ayds3qi fram_buff (
		.data_a    (data_a),    //  ram_input.datain_a
		.data_b    (data_b),    //           .datain_b
		.address_a (address_a), //           .address_a
		.address_b (address_b), //           .address_b
		.wren_a    (wren_a),    //           .wren_a
		.wren_b    (wren_b),    //           .wren_b
		.clock_a   (clock_a),   //           .clock_a
		.clock_b   (clock_b),   //           .clock_b
		.q_a       (q_a),       // ram_output.dataout_a
		.q_b       (q_b)        //           .dataout_b
	);

endmodule
